[mdzk]
backlinks-header = "Backlinks"
authors = ["wylited"]
language = "en"
multilingual = false
src = "notes"
title = "Wylinotes"
ignore = [
    "templates/",
    ".obsidian/",
]

[output.html]
site-url = "/wylinotes"
copy-fonts = true
no-section-label = true

[output.html.fold]
enable = true