[mdzk]
authors = ["wylited"]
ignore = [
    "Templates/",
    ".obsidian/",
    "to be cleaned/",
    "Organisation/",
]
language = "en"
multilingual = false
src = "notes"
title = "wylinotes"
description = "A brain of knowledge I made, because I don't have one."


[output.html]
site-url = "/wylinotes"
copy-fonts = false
no-section-label = true

[output.html.fold]
enable = true

[style]
sidebar-width = "200px"
bg = "#0D1718"
fg = "#BFBDB6"

sidebar-bg = "#1c1e22"
sidebar-fg = "#CCCAC2"
sidebar-nonexistent = "#999893"
sidebar-active = "#D95757"
sidebar-spacer = "#222"

scrollbar = "#2b2b2b"

icons = "#999"
icons-hover = "#D95757"

links = "#5CCFE6"

inline-code-color = "#0D1017"

quote-bg = "#0D1017"
quote-border = "#FFD173"

searchbar-border-color = "#D95757"
searchbar-bg = "#1c1e22"
searchbar-fg = "#BFBDB6"
searchbar-shadow-color = "#000"
searchresults-header-fg = "#CCCAC2"
searchresults-border-color = "#D95757" 

watermark = "false"
